### ISSUE TITLE
Variable 'err' referenced before assignment

### ISSUE THREAD

**Issue by jwallden** [RomelTorres/alpha_vantage#8] opened 2017-06-10 22:08 UTC
When trying to fetch data for a symbol that does not exist in the api i get the following:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    outputsize='compact')
  File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 152, in _format_wrapper
    json_response, data_key, meta_data_key = func(self, *args, **kwargs)
  File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 138, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
  File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 76, in _retry_wrapper
    raise ValueError(err)
UnboundLocalError: local variable 'err' referenced before assignment

**Comment by RomelTorres** [comment] 2017-06-11 20:02
Hello there, 

Sorry for the late respose, i have been travelling for work.This issue has been solved in the last version of the package 1.1.4, it looks like you haven't upgraded the package. Could you please upgrade the package to the last version? I will close the issue since I can't reproduce it, if it still fails please reopen and I'll look further into it.

Best regards,

Romel

**Closed** 2017-06-11 20:02 UTC
Labels: duplicate
