### ISSUE TITLE
issue with the API call when outputsize=full

### ISSUE THREAD

**Issue by DanielPNewman** [RomelTorres/alpha_vantage#173] opened 2019-12-10 10:55 UTC
Hello, I found this bug while using the python wrapper, but narrowed it down to the API call itself (@PatrickAlphaVantage - maybe similar to #150 but slightly different symptoms):

TIME_SERIES_DAILY_ADJUSTED returns data when **outputsize=compact**, but throws an error when **outputsize=full**, for some tickers/symbols, e.g....

No problems with the API when symbol=ILB.AX and **outputsize=compact**:  
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=ILB.AX&apikey=MY_ALPHAVANTAGE_KEY&outputsize=compact ...returns data as expected.

But when **outputsize=full** it returns this error **"Error Message": "Invalid API call"**: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=ILB.AX&apikey=MY_ALPHAVANTAGE_KEY&outputsize=full 

:exclamation: obviously **MY_ALPHAVANTAGE_KEY** above must to be substituted to a valid key to run these examples - thought it best not to put my personal api key here :sweat_smile:

**Comment by PatrickAlphaVantage** [comment] 2019-12-11 04:26
Yup, looks like the same issue. When a few data point from the farther back don’t pass our QA we only serve the compact version. 

We have to go back and manual fix/figure out what the issue is.

Thanks for the issue

**Comment by DanielPNewman** [comment] 2019-12-12 02:39
Ah oh, makes sense. Same issue for `symbol=QCB.AX` , FYI.

I love alpha_vantage, such a great product, keep up the good work!

**Comment by PatrickAlphaVantage** [comment] 2019-12-12 16:57
Woot woot!! Thank you!

**Comment by PatrickAlphaVantage** [comment] 2019-12-12 16:58
Closing due to duplicate

**Closed by PatrickAlphaVantage** 2019-12-12 16:58 UTC
Labels: av_issue, duplicate
