### ISSUE TITLE
async_support.timeseries

### ISSUE THREAD

**Issue by adamantium1987** [RomelTorres/alpha_vantage#378] opened 2024-07-26 15:08 UTC
When using the code in the readme (see below). I get the following error on the TimeSeries import

"Cannot find reference 'TimeSeries' in 'timeseries.py' "

import asyncio
from alpha_vantage.async_support.timeseries import TimeSeries

symbols = ['AAPL', 'GOOG', 'TSLA', 'MSFT']

async def get_data(symbol):
    ts = TimeSeries(key='YOUR_KEY_HERE')
    data, _ = await ts.get_quote_endpoint(symbol)
    await ts.close()
    return data

loop = asyncio.get_event_loop()
tasks = [get_data(symbol) for symbol in symbols]
group1 = asyncio.gather(*tasks)
results = loop.run_until_complete(group1)
loop.close()
print(results)

**Comment by AlphaVantageSupport** [comment] 2024-07-30 04:55
Closing this for now as our team was unable to reproduce the issue. Will re-open if other users report similar issues.

**Closed as completed by AlphaVantageSupport** 2024-07-30 04:55 UTC

**Comment by adamantium1987** [comment] 2024-08-07 19:02
I copied and pasted that code directly from the readme into my IDE, after installing the alpha_vantage python package, are there any steps that I am missing ?

**Comment by AlphaVantageSupport** [comment] 2024-08-07 20:05
Please try uninstall and then reinstall the library with pip
