### ISSUE TITLE
Incorrect and Variable Number of DataPoints

### ISSUE THREAD

**Issue by CalumTowler** [RomelTorres/alpha_vantage#170] opened 2019-12-08 18:55 UTC
When using the "stockdata, meta_stockdata = ts.get_intraday(self.ticker,'1min','full')" call, the data returned should 1950 datapoints but almost never exceeds 1938. Upon inspection of the dataset, random time intervals are missing. The number of these is not consistent over tickers, meaning that datasets are different lengths with different points missing. Is this isolated to me or have you noticed this happening before? 
Let me know if you want me to attach everything, but as it was simply the data call I thought I might not need to. The tickers I've been testing this on are MSFT MU and FB, and I've been testing on the dataset from 02/12 - 06/12.

**Comment by PatrickAlphaVantage** [comment] 2019-12-10 08:32
Great question. Here is a simple way to test it, and see what keys are different. 

I'm not sure at the moment, I can look more into it when I get back (I'm on vacation ❤️ )

Unless someone else has some insight. 
```
import alpha_vantage
import pandas

from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries()
data, meta_data = ts.get_intraday(interval='1min', symbol='MSFT', outputsize='full')
data2, meta_data2 = ts.get_intraday(interval='1min', symbol='TSLA', outputsize='full')
print(len(data2))
print(len(data))
print(set(data.keys()).difference(data2.keys()))
```

**Comment by CalumTowler** [comment] 2019-12-10 08:34
Awesome I’ll have a play. Enjoy your holiday man - thanks for replying so quickly!

On 10 Dec 2019, at 08:32, Patrick Collins <notifications@github.com> wrote:

﻿

Great question. Here is a simple way to test it, and see what keys are different.

I'm not sure at the moment, I can look more into it when I get back (I'm on vacation ❤️ )

Unless someone else has some insight.

import alpha_vantage
import pandas

from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries()
data, meta_data = ts.get_intraday(interval='1min', symbol='MSFT', outputsize='full')
data2, meta_data2 = ts.get_intraday(interval='1min', symbol='TSLA', outputsize='full')
print(len(data2))
print(len(data))
print(set(data.keys()).difference(data2.keys()))

**Comment by CalumTowler** [comment] 2019-12-19 12:14
Have a bit more data:
Ran 4 tickers: MU, MSFT, NEM and FB. I was calling them last night so data is from 12  - 18 Dec. NEM and FB were giving me consistent dataset lengths of 1936 and 1938 respectively. I called them over 100 times and they did not change. For MU, the dataset varied between 1942 and 1938, and for MSFT, the same with 1941 and 1937. This was often in the pattern: 1938, 1938, ..., 1942, ..., 1938, rather than alternating between them. Let me know if you need more.

**Comment by PatrickAlphaVantage** [comment] 2019-12-19 17:37
Ah sorry for not getting back here. Yes this is a duplicate of #150. Thanks for following up. We are investigating why the intraday are skipping. For the moment, using GLOBAL_QUOTE will give you an accurate depiction.

**Closed by PatrickAlphaVantage** 2019-12-19 17:37 UTC
Labels: duplicate, question
