### ISSUE TITLE
displaying date data on x axis

### ISSUE THREAD

**Issue by lhubbard01** [RomelTorres/alpha_vantage#79] opened 2018-07-21 20:00 UTC
great framework, Im really impressed with it.  Having some trouble getting the x axis to display the ticks with their respective times/dates, running the tutorial on your api as is.  Any suggestions?

**Comment by czbo** [comment] 2018-08-12 12:57
this question is duplicate of #73 Missing values on x-axis. See my comment in that one.

**Closed** 2019-02-11 21:59 UTC
Labels: question
